FROM mysql:8.0

# Copy initialization script
COPY database/init.sql /docker-entrypoint-initdb.d/

# MySQL configuration
COPY my.cnf /etc/mysql/conf.d/my.cnf

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=tumicodes
ENV MYSQL_USER=tumicodes_user
ENV MYSQL_PASSWORD=user_password

# Expose MySQL port
EXPOSE 3306